# Generated by Django 2.2.3 on 2019-07-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('cast', models.CharField(max_length=1000)),
            ],
        ),
    ]
